import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar & Navigation
    dashboard: "Dashboard",
    map: "Interactive Map",
    ai_assistant: "AI Assistant",
    sustainability: "Sustainability",
    command_center: "Command Center",
    control_center: "Control Center",
    sign_out: "Sign Out",
    status: "Stadium Status",
    secure: "SECURE",
    evacuating: "EVACUATING",
    role: "Role",
    simulate_user: "Simulate User View",
    fan_view: "⚽ Fan View",
    staff_view: "🛡️ Stadium Staff",
    admin_view: "⚙️ Administrator",
    canopy_open: "Canopy Open",
    canopy_closed: "Canopy Closed",

    // Landing Page
    hero_badge: "The Future of Tournament Operations is Here",
    hero_title: "Next-Gen AI Intelligence for Smart World Cup Stadiums",
    hero_subtitle: "StadiumMind AI streamlines fan navigation, crowd flow analytics, security dispatch, multilingual accessibility, and carbon offsets for the FIFA World Cup 2026.",
    launch_btn: "Launch Dashboard",
    admin_sim_btn: "Admin Panel Simulation",
    stats_fans: "Live Stadium Fans",
    stats_wait: "Avg Gate Queue",
    stats_latency: "Gemini AI Latency",
    stats_ada: "ADA Compliant Routes",
    modules_title: "Platform Core Modules",
    modules_sub: "Designed for Fans & Coordinators",
    module_ai_title: "Multilingual Gemini Assistant",
    module_ai_desc: "Real-time Google Gemini integrations providing voice-enabled chat translations for international fans regarding entry gates, transport, and restrooms.",
    module_map_title: "Interactive OpenStreetMap",
    module_map_desc: "Dynamic Leaflet map container displaying zones, parking lot hubs, medical care tents, food court congestion levels, and customizable wheelchair routing.",
    module_command_title: "Command & Dispatch Center",
    module_command_desc: "Simulated real-time camera security feeds, direct emergency notification triggers, incident status monitoring, and physical gate lock toggling tools.",
    module_sustain_title: "Sustainability Gamification",
    module_sustain_desc: "Track carbon footprint reductions, scan Meadowlands Transit tickets to complete challenges, and earn Eco-Points redeemable for venue concession discounts.",
    module_telemetry_title: "Live Telemetry Simulations",
    module_telemetry_desc: "Interactive simulators feeding live energy draws, water levels, crowd flow estimations, incident logs, and scoreboard metrics directly from the Field.",
    module_transit_title: "Public Transit Integration",
    module_transit_desc: "Keep fans informed with departures times, delays, and passenger capacity indexes for transit links, buses, rideshares, and shuttle lines.",

    // Smart Dashboard
    dashboard_title: "Smart Stadium Dashboard",
    dashboard_subtitle: "FIFA World Cup 2026 Operations & Fan telemetry dashboard.",
    live_match: "LIVE MATCH",
    home: "HOME",
    away: "AWAY",
    attendance: "Attendance",
    possession: "Possession",
    bottlenecks: "Ingress Bottlenecks",
    wait_time: "Wait Time",
    recommended: "Recommended",
    weather_title: "Weather & Conditions",
    clear_sky: "Clear Skies",
    solar_canopy: "Stadium Canopy",
    precipitation: "Precipitation Chance",
    occupancy_curve: "Stadium Occupancy Curve",
    occupancy_sub: "Accumulated entry flow from gates opening.",
    transit_guide: "Departure Transit Guide",
    departs: "Departs",
    destination: "Dest",
    ada_notice: "Need wheelchair-accessible shuttles? Request an ADA ride-share picker or find transit ramps at Lot P4.",

    // Map
    filter_all: "All",
    filter_gates: "Gates",
    filter_parking: "Parking",
    filter_medical: "Medical",
    filter_restrooms: "Restrooms",
    filter_dining: "Dining",
    filter_safety: "Safety Routes",
    landmark_title: "Select Stadium Landmark",
    landmark_sub: "Click any gate, parking lot, or medical tent icon on the map to query queues, accessibility, and navigate.",
    location_code: "Location Code",
    directions_title: "Compute Directions",
    direct_path: "Direct Path",
    ada_route: "ADA Route",
    calculated_badge: "CALCULATED",
    starting_loc: "Simulated starting location: Section 100 Outer Circle.",

    // AI Assistant
    ai_title: "StadiumMind Assistant",
    ai_info_title: "AIAssistant Info",
    ai_info_1: "Multilingual Navigation: Translates requests instantly to guide fans through concessions, gates, and transit options.",
    ai_info_2: "Connected Mapping: Typing 'Nearest medical center' will calculate the path on the maps panel.",
    ai_info_3: "Speech Access: Voice assist and text-to-speech capabilities accommodate visually/auditorily impaired fans.",
    ai_info_4: "Eco-Recycling Hub: Resolves where reverse vending machines are located, rewarding eco-challenges points.",
    ai_access_title: "Accessibility Support",
    ai_access_desc: "Enable sensory accessibility filters to map quiet-zones, elevator towers, or wheelchair companion ramps.",
    ai_placeholder: "Ask StadiumMind AI...",
    ai_listening: "Listening to query...",

    // Command Center
    cc_title: "Security Command Center",
    cc_subtitle: "Live operational dispatch and surveillance monitoring center.",
    cc_threat: "Multi-Cam Threat Detection AI",
    cc_active: "Active Incidents & Staff Dispatch",
    cc_no_incidents: "No active security or medical incidents. Stadium is secure.",
    cc_dispatch: "Dispatch Team",
    cc_confirm: "Confirm On-Scene",
    cc_resolve: "Mark Resolved",
    cc_gate_lock: "Entry Gate Control Panel",
    cc_lock_desc: "Override IoT gates status during lockouts or evacuations.",
    cc_report_alarm: "Report Local Alarm",
    cc_alarm_title: "Alarm Title",
    cc_alarm_loc: "Stadium Location",
    cc_alarm_severity: "Severity Level",
    cc_alarm_log_btn: "Log New Incident",
    cc_logs: "Live Operational Log",

    // Sustainability
    sus_title: "Eco-Stadium Intelligence",
    sus_subtitle: "Green telemetry dashboard mapping solar yield, recycling goals, and fan gamification.",
    sus_score: "Your Eco Score",
    sus_points: "Points",
    sus_next_reward: "Next Reward: 300 pts",
    sus_redeem: "Redeem concession voucher",
    sus_canopy_yield: "Solar Canopy Yield",
    sus_canopy_desc: "Generating 18.5% of current stadium grid load.",
    sus_grid_power: "Grid Power",
    sus_offset: "Offset: 34.2 tons CO₂",
    sus_recycle_target: "Recycling Target",
    sus_recycle_desc: "Goal: 70% recycling of match plastic disposables.",
    sus_recycle_vending: "Reverse Vending",
    sus_recycle_exceeding: "Exceeding Target",
    sus_challenges: "Complete Active Fan Eco-Challenges",
    sus_claim_pts: "Claim Eco-Points",
    sus_completed: "Completed",
    sus_solar_integration: "Renewable Solar Integration (kW Draw)",
    sus_waste_analytics: "Waste Analytics (Tons)",
    sus_leaderboard: "Fan Leaderboard",
    sus_you: "You (Simulated)",

    // Auth
    auth_register: "Create Account",
    auth_signin: "Authenticate Credentials",
    auth_fullname: "Full Name",
    auth_email: "Email Address",
    auth_password: "Password",
    auth_bypass: "Developer / Judge Quick Bypass",
    auth_processing: "Processing session...",
    auth_create_account: "Create Account",
    auth_toggle_create: "Don't have an account? Create one",
    auth_toggle_login: "Already have an account? Sign In",

    // Alerts
    alert_evac_title: "Emergency Evacuation Active",
    alert_evac_desc: "Please proceed calmly to the nearest open exit gates: Exit North or Exit South. Follow safety marshals. DO NOT USE ELEVATORS.",
    alert_sos_title: "Active SOS Distress Signal",
    alert_sos_desc: "Distress beacon active near Section 220 Concourse. First responders have been dispatched.",
    alert_sos_clear: "Clear SOS"
  },
  es: {
    // Sidebar & Navigation
    dashboard: "Panel de Control",
    map: "Mapa Interactivo",
    ai_assistant: "Asistente de IA",
    sustainability: "Sostenibilidad",
    command_center: "Centro de Comando",
    control_center: "Centro de Control",
    sign_out: "Cerrar Sesión",
    status: "Estado del Estadio",
    secure: "SEGURO",
    evacuating: "EVACUANDO",
    role: "Rol",
    simulate_user: "Simular Vista de Usuario",
    fan_view: "⚽ Vista de Fan",
    staff_view: "🛡️ Personal del Estadio",
    admin_view: "⚙️ Administrador",
    canopy_open: "Techo Abierto",
    canopy_closed: "Techo Cerrado",

    // Landing Page
    hero_badge: "El futuro de las operaciones del torneo ya está aquí",
    hero_title: "Inteligencia de IA de próxima generación para estadios inteligentes",
    hero_subtitle: "StadiumMind AI agiliza la navegación de los aficionados, el análisis de flujo de multitudes, el despacho de seguridad, la accesibilidad multilingüe y la compensación de carbono para la Copa Mundial de la FIFA 2026.",
    launch_btn: "Iniciar Panel",
    admin_sim_btn: "Simulación de Panel de Admin",
    stats_fans: "Fans en el Estadio",
    stats_wait: "Cola Promedio en Puertas",
    stats_latency: "Latencia de Gemini AI",
    stats_ada: "Rutas con Acceso ADA",
    modules_title: "Módulos Centrales de la Plataforma",
    modules_sub: "Diseñado para Fans y Coordinadores",
    module_ai_title: "Asistente Multilingüe Gemini",
    module_ai_desc: "Integraciones de Google Gemini en tiempo real que ofrecen traducciones de chat por voz para aficionados internacionales sobre puertas de entrada, transporte y baños.",
    module_map_title: "Mapa Interactivo OpenStreetMap",
    module_map_desc: "Contenedor de mapa dinámico Leaflet que muestra zonas, estacionamientos, puestos médicos, congestión en patios de comida y rutas para sillas de ruedas.",
    module_command_title: "Centro de Comando y Despacho",
    module_command_desc: "Cámaras de seguridad en tiempo real, alertas de emergencia, monitoreo de incidentes y control de cierre de puertas.",
    module_sustain_title: "Sostenibilidad Gamificada",
    module_sustain_desc: "Monitorea la reducción de carbono, escanea boletos de tránsito para completar desafíos y gana Eco-Puntos canjeables por descuentos en comida.",
    module_telemetry_title: "Simulaciones de Telemetría",
    module_telemetry_desc: "Simuladores que envían datos de consumo eléctrico, niveles de agua, flujos de multitud e incidentes en tiempo real.",
    module_transit_title: "Integración de Tránsito Público",
    module_transit_desc: "Mantiene informados a los fans sobre horarios de salida de trenes, autobuses, áreas de Uber/Lyft y retrasos.",

    // Smart Dashboard
    dashboard_title: "Panel Inteligente del Estadio",
    dashboard_subtitle: "Panel de operaciones de la Copa Mundial de la FIFA 2026 y telemetría de aficionados.",
    live_match: "PARTIDO EN VIVO",
    home: "LOCAL",
    away: "VISITANTE",
    attendance: "Asistencia",
    possession: "Posesión",
    bottlenecks: "Cuellos de Botella de Entrada",
    wait_time: "Tiempo de Espera",
    recommended: "Recomendado",
    weather_title: "Clima y Condiciones",
    clear_sky: "Cielo Despejado",
    solar_canopy: "Techo del Estadio",
    precipitation: "Probabilidad de Lluvia",
    occupancy_curve: "Curva de Ocupación del Estadio",
    occupancy_sub: "Flujo de entrada acumulado desde la apertura de puertas.",
    transit_guide: "Guía de Salida de Tránsito",
    departs: "Sale en",
    destination: "Dest",
    ada_notice: "¿Necesita transporte accesible para sillas de ruedas? Solicite un vehículo ADA o busque las rampas de tránsito en el Lote P4.",

    // Map
    filter_all: "Todo",
    filter_gates: "Puertas",
    filter_parking: "Estacionamiento",
    filter_medical: "Médico",
    filter_restrooms: "Baños",
    filter_dining: "Comidas",
    filter_safety: "Rutas de Seguridad",
    landmark_title: "Seleccione Punto del Estadio",
    landmark_sub: "Haga clic en cualquier puerta, estacionamiento o puesto médico en el mapa para ver colas, accesibilidad y rutas.",
    location_code: "Código de Ubicación",
    directions_title: "Calcular Ruta",
    direct_path: "Ruta Directa",
    ada_route: "Ruta ADA",
    calculated_badge: "CALCULADA",
    starting_loc: "Punto de partida simulado: Círculo Exterior Sección 100.",

    // AI Assistant
    ai_title: "Asistente StadiumMind",
    ai_info_title: "Información de Asistente IA",
    ai_info_1: "Navegación Multilingüe: Traduce solicitudes al instante para guiar a los fans por puestos de comida, puertas y tránsito.",
    ai_info_2: "Mapeo Conectado: Al escribir 'Puesto médico más cercano' se calculará la ruta en el panel de mapas.",
    ai_info_3: "Acceso por Voz: Funciones de asistencia por voz y texto a voz para fans con dificultades visuales o auditivas.",
    ai_info_4: "Centro de Reciclaje Eco: Ubica máquinas de reciclaje inverso RVM, otorgando puntos de desafíos ecológicos.",
    ai_access_title: "Soporte de Accesibilidad",
    ai_access_desc: "Active filtros de accesibilidad sensorial para mapear zonas tranquilas, ascensores o rampas para sillas de ruedas.",
    ai_placeholder: "Pregunte a StadiumMind AI...",
    ai_listening: "Escuchando consulta...",

    // Command Center
    cc_title: "Centro de Comando de Seguridad",
    cc_subtitle: "Centro de despacho operativo en vivo y monitoreo de vigilancia.",
    cc_threat: "IA de Detección de Amenazas Multi-Cámara",
    cc_active: "Incidentes Activos y Despacho de Personal",
    cc_no_incidents: "No hay incidentes de seguridad o médicos activos. Estadio seguro.",
    cc_dispatch: "Despachar Equipo",
    cc_confirm: "Confirmar en Escena",
    cc_resolve: "Marcar Resuelto",
    cc_gate_lock: "Panel de Control de Puertas",
    cc_lock_desc: "Anular el estado de las puertas IoT durante cierres o evacuaciones.",
    cc_report_alarm: "Reportar Alarma Local",
    cc_alarm_title: "Título de la Alarma",
    cc_alarm_loc: "Ubicación en el Estadio",
    cc_alarm_severity: "Nivel de Severidad",
    cc_alarm_log_btn: "Registrar Incidente",
    cc_logs: "Registro Operativo en Vivo",

    // Sustainability
    sus_title: "Inteligencia Ecológica del Estadio",
    sus_subtitle: "Panel de telemetría verde que mapea rendimiento solar, metas de reciclaje y gamificación de fans.",
    sus_score: "Su Puntaje Eco",
    sus_points: "Puntos",
    sus_next_reward: "Siguiente Recompensa: 300 pts",
    sus_redeem: "Canjear cupón de comida",
    sus_canopy_yield: "Rendimiento Solar del Techo",
    sus_canopy_desc: "Generando el 18.5% de la carga eléctrica actual del estadio.",
    sus_grid_power: "Energía de Red",
    sus_offset: "Compensación: 34.2 ton CO₂",
    sus_recycle_target: "Meta de Reciclaje",
    sus_recycle_desc: "Meta: 70% de reciclaje de plásticos desechables.",
    sus_recycle_vending: "Reciclaje Inverso",
    sus_recycle_exceeding: "Superando Meta",
    sus_challenges: "Complete Desafíos Eco de Aficionados",
    sus_claim_pts: "Reclamar Eco-Puntos",
    sus_completed: "Completado",
    sus_solar_integration: "Integración Solar Renovable (Consumo kW)",
    sus_waste_analytics: "Análisis de Residuos (Toneladas)",
    sus_leaderboard: "Tabla de Clasificación Eco",
    sus_you: "Usted (Simulado)",

    // Auth
    auth_register: "Crear Cuenta",
    auth_signin: "Autenticar Credenciales",
    auth_fullname: "Nombre Completo",
    auth_email: "Correo Electrónico",
    auth_password: "Contraseña",
    auth_bypass: "Desvío Rápido de Desarrollador / Juez",
    auth_processing: "Procesando sesión...",
    auth_create_account: "Crear Cuenta",
    auth_toggle_create: "¿No tiene una cuenta? Regístrese",
    auth_toggle_login: "¿Ya tiene cuenta? Iniciar Sesión",

    // Alerts
    alert_evac_title: "Evacuación de Emergencia Activa",
    alert_evac_desc: "Proceda con calma a las puertas de salida abiertas más cercanas: Salida Norte o Salida Sur. Siga al personal de seguridad. NO USE ASCENSORES.",
    alert_sos_title: "Señal de Auxilio SOS Activa",
    alert_sos_desc: "Faro de auxilio activo cerca de la Sección 220 Concourse. Personal médico despachado.",
    alert_sos_clear: "Despejar SOS"
  },
  fr: {
    // Sidebar & Navigation
    dashboard: "Tableau de Bord",
    map: "Carte Interactive",
    ai_assistant: "Assistant IA",
    sustainability: "Durabilité",
    command_center: "Centre de Commande",
    control_center: "Centre de Contrôle",
    sign_out: "Se Déconnecter",
    status: "État du Stade",
    secure: "SÉCURISÉ",
    evacuating: "ÉVACUATION",
    role: "Rôle",
    simulate_user: "Simuler la Vue Utilisateur",
    fan_view: "⚽ Vue Supporter",
    staff_view: "🛡️ Personnel du Stade",
    admin_view: "⚙️ Administrateur",
    canopy_open: "Toit Ouvert",
    canopy_closed: "Toit Fermé",

    // Landing Page
    hero_badge: "L'avenir des opérations de tournois est arrivé",
    hero_title: "IA de Nouvelle Génération pour Stades Intelligents",
    hero_subtitle: "StadiumMind AI simplifie la navigation des fans, l'analyse du flux de foule, le dispatching de sécurité, l'accessibilité multilingue et la compensation carbone pour la Coupe du Monde de la FIFA 2026.",
    launch_btn: "Lancer le Tableau de Bord",
    admin_sim_btn: "Simulation du Panneau d'Administration",
    stats_fans: "Supporters Présents",
    stats_wait: "Attente Moyenne aux Portes",
    stats_latency: "Latence Gemini AI",
    stats_ada: "Itinéraires Accessibles ADA",
    modules_title: "Modules Centraux de la Plateforme",
    modules_sub: "Conçu pour les Supporters et Coordinateurs",
    module_ai_title: "Assistant Gemini Multilingue",
    module_ai_desc: "Intégrations en temps réel de Google Gemini offrant des traductions vocales pour les supporters internationaux concernant les entrées, transports et toilettes.",
    module_map_title: "Carte Interactive OpenStreetMap",
    module_map_desc: "Carte dynamique Leaflet affichant les zones, parkings, postes médicaux, affluence des restaurants et itinéraires PMR personnalisés.",
    module_command_title: "Centre de Commande & Dispatching",
    module_command_desc: "Flux vidéo de caméras en temps réel, alertes d'urgence, suivi des incidents et contrôle de verrouillage des portes physiques.",
    module_sustain_title: "Éco-Durabilité Ludique",
    module_sustain_desc: "Suivez la réduction d'empreinte carbone, scannez vos tickets de transport pour valider les défis et gagnez des Éco-Points échangeables.",
    module_telemetry_title: "Simulations de Télémétrie",
    module_telemetry_desc: "Simulateurs affichant la charge électrique en temps réel, les niveaux d'eau, le flux de foule et le score de la rencontre.",
    module_transit_title: "Intégration des Transports Publics",
    module_transit_desc: "Informations en direct sur les départs de trains, bus navettes, zones de covoiturage et état du trafic.",

    // Smart Dashboard
    dashboard_title: "Tableau de Bord Intelligent",
    dashboard_subtitle: "Tableau de bord des opérations de la Coupe du Monde de la FIFA 2026 et télémétrie des fans.",
    live_match: "MATCH EN DIRECT",
    home: "DOMICILE",
    away: "EXTÉRIEUR",
    attendance: "Affluence",
    possession: "Possession",
    bottlenecks: "Files d'Attente aux Entrées",
    wait_time: "Temps d'Attente",
    recommended: "Recommandé",
    weather_title: "Météo et Conditions",
    clear_sky: "Ciel Dégagé",
    solar_canopy: "Toit du Stade",
    precipitation: "Risque de Pluie",
    occupancy_curve: "Courbe d'Affluence du Stade",
    occupancy_sub: "Flux d'entrée cumulé depuis l'ouverture des portes.",
    transit_guide: "Guide des Transports de Départ",
    departs: "Départ dans",
    destination: "Dest",
    ada_notice: "Besoin d'une navette accessible PMR? Demandez un transport ADA ou rendez-vous aux rampes de transit du parking P4.",

    // Map
    filter_all: "Tout",
    filter_gates: "Portes",
    filter_parking: "Parkings",
    filter_medical: "Médical",
    filter_restrooms: "Toilettes",
    filter_dining: "Restauration",
    filter_safety: "Sorties de Secours",
    landmark_title: "Sélectionnez un Repère",
    landmark_sub: "Cliquez sur une porte, un parking ou un poste médical pour voir l'attente, l'accessibilité et calculer un itinéraire.",
    location_code: "Code de Localisation",
    directions_title: "Calculer l'Itinéraire",
    direct_path: "Chemin Direct",
    ada_route: "Itinéraire PMR",
    calculated_badge: "CALCULÉ",
    starting_loc: "Point de départ simulé: Section 100 Cercle Extérieur.",

    // AI Assistant
    ai_title: "Assistant StadiumMind",
    ai_info_title: "Infos de l'Assistant IA",
    ai_info_1: "Navigation Multilingue: Traduit les requêtes instantanément pour guider les fans à travers les restaurants, entrées et transports.",
    ai_info_2: "Itinéraire Connecté: Taper 'Poste médical le plus proche' affichera le chemin sur le panneau de cartes.",
    ai_info_3: "Accès Vocal: Fonctions d'assistance vocale et lecture audio pour les personnes malvoyantes ou malentendantes.",
    ai_info_4: "Recyclage Éco: Indique les machines de recyclage inverse RVM et valide les défis écologiques.",
    ai_access_title: "Aide à l'Accessibilité",
    ai_access_desc: "Activez les filtres d'accessibilité sensorielle pour trouver les zones calmes, les ascenseurs ou les rampes d'accès.",
    ai_placeholder: "Demander à StadiumMind AI...",
    ai_listening: "Écoute en cours...",

    // Command Center
    cc_title: "Centre de Commande de Sécurité",
    cc_subtitle: "Centre de répartition opérationnel en direct et surveillance vidéo.",
    cc_threat: "IA de Détection des Menaces Multi-Caméras",
    cc_active: "Incidents Actifs et Envoi de Personnel",
    cc_no_incidents: "Aucun incident de sécurité ou médical actif. Stade sécurisé.",
    cc_dispatch: "Envoyer l'Équipe",
    cc_confirm: "Confirmer sur Place",
    cc_resolve: "Marquer Résolu",
    cc_gate_lock: "Panneau de Contrôle des Portes",
    cc_lock_desc: "Forcer le statut des portes IoT lors d'un confinement ou d'une évacuation.",
    cc_report_alarm: "Signaler une Alarme",
    cc_alarm_title: "Titre de l'Alarme",
    cc_alarm_loc: "Emplacement dans le Stade",
    cc_alarm_severity: "Niveau de Gravité",
    cc_alarm_log_btn: "Enregistrer l'Incident",
    cc_logs: "Journal Opérationnel en Direct",

    // Sustainability
    sus_title: "Éco-Stade Intelligent",
    sus_subtitle: "Tableau de bord de télémétrie verte: production solaire, objectifs de recyclage et défis écologiques.",
    sus_score: "Votre Éco-Score",
    sus_points: "Points",
    sus_next_reward: "Prochaine Récompense: 300 pts",
    sus_redeem: "Échanger contre un bon restaurant",
    sus_canopy_yield: "Production des Panneaux Solaires",
    sus_canopy_desc: "Génère 18.5% de la charge électrique actuelle du stade.",
    sus_grid_power: "Énergie du Réseau",
    sus_offset: "Évité: 34.2 tonnes de CO₂",
    sus_recycle_target: "Taux de Recyclage",
    sus_recycle_desc: "Objectif: 70% de recyclage des plastiques du match.",
    sus_recycle_vending: "Collecteurs RVM",
    sus_recycle_exceeding: "Objectif Dépassé",
    sus_challenges: "Valider les Défis Écologiques Supporter",
    sus_claim_pts: "Réclamer les Éco-Points",
    sus_completed: "Terminé",
    sus_solar_integration: "Intégration Solaire Renouvelable (kW Consommé)",
    sus_waste_analytics: "Analyse des Déchets (Tonnes)",
    sus_leaderboard: "Classement des Supporters",
    sus_you: "Vous (Simulé)",

    // Auth
    auth_register: "Créer un Compte",
    auth_signin: "Connexion Sécurisée",
    auth_fullname: "Nom Complet",
    auth_email: "Adresse Email",
    auth_password: "Mot de passe",
    auth_bypass: "Raccourcis Démo (Développeur / Juge)",
    auth_processing: "Traitement de la session...",
    auth_create_account: "S'enregistrer",
    auth_toggle_create: "Pas de compte? Créez-en un",
    auth_toggle_login: "Déjà un compte? Connectez-vous",

    // Alerts
    alert_evac_title: "Évacuation d'Urgence Active",
    alert_evac_desc: "Veuillez vous diriger calmement vers les sorties ouvertes: Sortie Nord ou Sortie Sud. Suivez les consignes. N'UTILISEZ PAS LES ASCENSEURS.",
    alert_sos_title: "Signal de Détresse SOS Actif",
    alert_sos_desc: "Balise de détresse active dans la Section 220. Les premiers secours sont en route.",
    alert_sos_clear: "Effacer SOS"
  },
  de: {
    // Sidebar & Navigation
    dashboard: "Dashboard",
    map: "Interaktive Karte",
    ai_assistant: "KI-Assistent",
    sustainability: "Nachhaltigkeit",
    command_center: "Kommandozentrale",
    control_center: "Kontrollzentrum",
    sign_out: "Abmelden",
    status: "Stadionstatus",
    secure: "GESICHERT",
    evacuating: "EVAKUIERUNG",
    role: "Rolle",
    simulate_user: "Benutzeransicht simulieren",
    fan_view: "⚽ Fan-Ansicht",
    staff_view: "🛡️ Stadionpersonal",
    admin_view: "⚙️ Administrator",
    canopy_open: "Dach Geöffnet",
    canopy_closed: "Dach Geschlossen",

    // Landing Page
    hero_badge: "Die Zukunft des Turnierbetriebs ist da",
    hero_title: "KI-Intelligenz der nächsten Generation für Smart-Stadiums",
    hero_subtitle: "StadiumMind AI optimiert die Navigation der Fans, die Analyse des Zuschauerflusses, den Sicherheitsdienst, die mehrsprachige Barrierefreiheit und den CO₂-Ausgleich für die FIFA Fussball-Weltmeisterschaft 2026.",
    launch_btn: "Dashboard öffnen",
    admin_sim_btn: "Admin-Panel-Simulation",
    stats_fans: "Fans im Stadion",
    stats_wait: "Durchschnittliche Warteschlange",
    stats_latency: "Gemini KI-Latenz",
    stats_ada: "Barrierefreie Routen",
    modules_title: "Kernmodule der Plattform",
    modules_sub: "Entwickelt für Fans und Koordinatoren",
    module_ai_title: "Mehrsprachiger Gemini-Assistent",
    module_ai_desc: "Echtzeit-Google-Gemini-Integrationen mit sprachaktivierten Chat-Übersetzungen für internationale Fans zu Toren, Verkehrsmitteln und Toiletten.",
    module_map_title: "Interaktive OpenStreetMap",
    module_map_desc: "Dynamischer Leaflet-Kartencontainer, der Zonen, Parkplätze, Sanitätszelte, die Auslastung der Gastronomie und Rollstuhlrouten anzeigt.",
    module_command_title: "Kommando- & Einsatzzentrale",
    module_command_desc: "Sicherheitskamera-Feeds in Echtzeit, direkte Notfallalarme, Vorfallsüberwachung und physische Torsperren.",
    module_sustain_title: "Nachhaltigkeit Spielerisch",
    module_sustain_desc: "Verfolgen Sie die Reduzierung Ihres CO₂-Fußabdrucks, scannen Sie ÖPNV-Tickets und sammeln Sie einlösbare Eco-Punkte.",
    module_telemetry_title: "Echtzeit-Telemetrie-Simulationen",
    module_telemetry_desc: "Simulatoren, die den aktuellen Stromverbrauch, Wasserstände, Besucherströme und das Spielergebnis übertragen.",
    module_transit_title: "ÖPNV-Integration",
    module_transit_desc: "Informiert Fans über Abfahrtszeiten von Zügen und Bussen, Verspätungen sowie Uber/Lyft-Sammelpunkte.",

    // Smart Dashboard
    dashboard_title: "Intelligentes Stadion-Dashboard",
    dashboard_subtitle: "FIFA Fussball-Weltmeisterschaft 2026 Betriebs- & Fan-Telemetriedaten.",
    live_match: "LIVE-SPIEL",
    home: "HEIM",
    away: "AUSWÄRTS",
    attendance: "Zuschauer",
    possession: "Ballbesitz",
    bottlenecks: "Einlass-Engpässe",
    wait_time: "Wartezeit",
    recommended: "Empfohlen",
    weather_title: "Wetter & Bedingungen",
    clear_sky: "Klarer Himmel",
    solar_canopy: "Stadiondach",
    precipitation: "Regenwahrscheinlichkeit",
    occupancy_curve: "Stadionauslastung",
    occupancy_sub: "Kumulierter Einlassstrom seit Toröffnung.",
    transit_guide: "Abreise-Verkehrsführer",
    departs: "Abfahrt in",
    destination: "Ziel",
    ada_notice: "Benötigen Sie einen rollstuhlgerechten Shuttle? Fordern Sie eine ADA-Fahrt an oder finden Sie Rampen an Parkplatz P4.",

    // Map
    filter_all: "Alle",
    filter_gates: "Tore",
    filter_parking: "Parkplätze",
    filter_medical: "Sanitäter",
    filter_restrooms: "Toiletten",
    filter_dining: "Gastronomie",
    filter_safety: "Fluchtwege",
    landmark_title: "Wählen Sie eine Sehenswürdigkeit",
    landmark_sub: "Klicken Sie auf ein Tor, einen Parkplatz oder eine Sanitätsstation, um Wartezeiten, Barrierefreiheit und Routen anzuzeigen.",
    location_code: "Standortcode",
    directions_title: "Wegbeschreibung berechnen",
    direct_path: "Direkter Weg",
    ada_route: "ADA-Route",
    calculated_badge: "BERECHNET",
    starting_loc: "Simulierter Startpunkt: Sektion 100 Äußerer Ring.",

    // AI Assistant
    ai_title: "StadiumMind Assistent",
    ai_info_title: "KI-Assistent Info",
    ai_info_1: "Mehrsprachige Navigation: Übersetzt Anfragen sofort, um Fans zu Gastronomie, Toren und ÖPNV zu leiten.",
    ai_info_2: "Verknüpfte Karten: Die Eingabe von 'Nächste Sanitätsstation' berechnet die Route auf der Karte.",
    ai_info_3: "Sprachsteuerung: Sprachassistent und Text-to-Speech-Funktionen unterstützen seh- oder hörgeschädigte Fans.",
    ai_info_4: "Eco-Recycling: Findet Recycling-Pfandautomaten (RVM) und belohnt Öko-Herausforderungen.",
    ai_access_title: "Unterstützung Barrierefreiheit",
    ai_access_desc: "Aktivieren Sie sensorische Filter, um Ruhezonen, Aufzüge oder Rollstuhlrampen anzuzeigen.",
    ai_placeholder: "Fragen Sie StadiumMind AI...",
    ai_listening: "Zuhören...",

    // Command Center
    cc_title: "Sicherheitskommandozentrale",
    cc_subtitle: "Live-Einsatzleitung und Videoüberwachung.",
    cc_threat: "Kameraüberwachung mit Bedrohungserkennungs-KI",
    cc_active: "Aktive Vorfälle & Personalentsendung",
    cc_no_incidents: "Keine aktiven Sicherheits- oder medizinischen Vorfälle. Stadion ist sicher.",
    cc_dispatch: "Team entsenden",
    cc_confirm: "Vor Ort bestätigen",
    cc_resolve: "Als gelöst markieren",
    cc_gate_lock: "Einlasstor-Bedienfeld",
    cc_lock_desc: "Überschreiben Sie den Status der IoT-Tore bei Sperrungen oder Evakuierungen.",
    cc_report_alarm: "Lokalen Alarm melden",
    cc_alarm_title: "Alarm-Titel",
    cc_alarm_loc: "Standort im Stadion",
    cc_alarm_severity: "Dringlichkeit",
    cc_alarm_log_btn: "Vorfall protokollieren",
    cc_logs: "Live-Betriebsprotokoll",

    // Sustainability
    sus_title: "Öko-Stadion-Intelligenz",
    sus_subtitle: "Nachhaltigkeits-Dashboard zur Darstellung von Solarertrag, Recyclingzielen und Fan-Ökopunkten.",
    sus_score: "Ihr Öko-Punktestand",
    sus_points: "Punkte",
    sus_next_reward: "Nächste Prämie: 300 Pkt",
    sus_redeem: "Gastronomie-Gutschein einlösen",
    sus_canopy_yield: "Ertrag der Solaranlage",
    sus_canopy_desc: "Erzeugt 18.5% der aktuellen Stadionlast.",
    sus_grid_power: "Netzstrom",
    sus_offset: "Vermeidung: 34.2 Tonnen CO₂",
    sus_recycle_target: "Recycling-Quote",
    sus_recycle_desc: "Ziel: 70% Recycling aller Einwegkunststoffe des Spiels.",
    sus_recycle_vending: "Pfandrückgabe (RVM)",
    sus_recycle_exceeding: "Ziel übertroffen",
    sus_challenges: "Aktive Öko-Herausforderungen für Fans",
    sus_claim_pts: "Öko-Punkte einfordern",
    sus_completed: "Abgeschlossen",
    sus_solar_integration: "Erneuerbare Solarenergie (kW Verbrauch)",
    sus_waste_analytics: "Abfallanalyse (Tonnen)",
    sus_leaderboard: "Fan-Bestenliste",
    sus_you: "Sie (Simuliert)",

    // Auth
    auth_register: "Konto erstellen",
    auth_signin: "Mit Anmeldedaten einloggen",
    auth_fullname: "Vollständiger Name",
    auth_email: "E-Mail-Adresse",
    auth_password: "Passwort",
    auth_bypass: "Entwickler- / Prüfer-Schnelleinstieg",
    auth_processing: "Sitzung wird verarbeitet...",
    auth_create_account: "Konto erstellen",
    auth_toggle_create: "Noch kein Konto? Registrieren",
    auth_toggle_login: "Bereits registriert? Einloggen",

    // Alerts
    alert_evac_title: "Notfallevakuierung Aktiv",
    alert_evac_desc: "Bitte begeben Sie sich ruhig zu den nächstgelegenen geöffneten Ausgängen: Ausgang Nord oder Ausgang Süd. Folgen Sie den Anweisungen. KEINE AUFZÜGE BENUTZEN.",
    alert_sos_title: "Aktives SOS-Notrufsignal",
    alert_sos_desc: "Notfunkbake aktiv nahe Sektion 220 Concourse. Rettungskräfte wurden entsandt.",
    alert_sos_clear: "SOS löschen"
  },
  pt: {
    // Sidebar & Navigation
    dashboard: "Painel de Controle",
    map: "Mapa Interativo",
    ai_assistant: "Assistente de IA",
    sustainability: "Sustentabilidade",
    command_center: "Centro de Comando",
    control_center: "Centro de Controle",
    sign_out: "Sair",
    status: "Status do Estádio",
    secure: "SEGURO",
    evacuating: "EVACUAÇÃO",
    role: "Função",
    simulate_user: "Simular Visualização de Usuário",
    fan_view: "⚽ Visão do Torcedor",
    staff_view: "🛡️ Equipe do Estádio",
    admin_view: "⚙️ Administrador",
    canopy_open: "Cobertura Aberta",
    canopy_closed: "Cobertura Fechada",

    // Landing Page
    hero_badge: "O futuro das operações de torneios está aqui",
    hero_title: "Inteligência de IA de última geração para estádios inteligentes",
    hero_subtitle: "O StadiumMind AI otimiza a navegação dos torcedores, análise do fluxo de multidões, despacho de segurança, acessibilidade multilíngue e compensação de carbono para a Copa do Mundo da FIFA 2026.",
    launch_btn: "Iniciar Painel",
    admin_sim_btn: "Simulação do Painel do Admin",
    stats_fans: "Torcedores no Estádio",
    stats_wait: "Fila Média nos Portões",
    stats_latency: "Latência do Gemini AI",
    stats_ada: "Rotas com Acesso ADA",
    modules_title: "Módulos Centrais da Plataforma",
    modules_sub: "Projetado para Torcedores e Coordenadores",
    module_ai_title: "Assistente Multilíngue Gemini",
    module_ai_desc: "Integrações do Google Gemini em tempo real que oferecem traduções de chat por voz para torcedores internacionais sobre portões, transporte e banheiros.",
    module_map_title: "Mapa Interativo OpenStreetMap",
    module_map_desc: "Contêiner de mapa dinâmico Leaflet que mostra zonas, estacionamento, postos médicos, praças de alimentação e rotas para cadeiras de rodas.",
    module_command_title: "Centro de Comando e Despacho",
    module_command_desc: "Câmeras de segurança em tempo real, alertas de emergência, monitoramento de incidentes e controle de trancamento de portões.",
    module_sustain_title: "Sustentabilidade Gamificada",
    module_sustain_desc: "Monitore a redução de carbono, escaneie bilhetes de transporte para completar desafios e ganhe Eco-Pontos resgatáveis.",
    module_telemetry_title: "Simulações de Telemetria",
    module_telemetry_desc: "Simuladores que transmitem consumo elétrico em tempo real, níveis de água, fluxo de multidão e placar da partida.",
    module_transit_title: "Integração de Transporte Público",
    module_transit_desc: "Mantém os torcedores informados sobre horários de saída de trens, ônibus, áreas de Uber/Lyft e atrasos.",

    // Smart Dashboard
    dashboard_title: "Painel Inteligente do Estádio",
    dashboard_subtitle: "Placar de operações da Copa do Mundo da FIFA 2026 e telemetria dos torcedores.",
    live_match: "PARTIDA AO VIVO",
    home: "MANDANTE",
    away: "VISITANTE",
    attendance: "Público",
    possession: "Posse de Bola",
    bottlenecks: "Gargalos de Entrada nos Portões",
    wait_time: "Tempo de Espera",
    recommended: "Recomendado",
    weather_title: "Clima e Condições",
    clear_sky: "Céu Limpo",
    solar_canopy: "Cobertura do Estádio",
    precipitation: "Probabilidade de Chuva",
    occupancy_curve: "Curva de Ocupação do Estádio",
    occupancy_sub: "Fluxo de entrada acumulado desde a abertura dos portões.",
    transit_guide: "Guia de Partida de Transporte",
    departs: "Partida em",
    destination: "Dest",
    ada_notice: "Precisa de transporte acessível para cadeira de rodas? Solicite um veículo ADA ou encontre as rampas de transporte no Lote P4.",

    // Map
    filter_all: "Todos",
    filter_gates: "Portões",
    filter_parking: "Estacionamento",
    filter_medical: "Médico",
    filter_restrooms: "Banheiros",
    filter_dining: "Alimentação",
    filter_safety: "Rotas de Segurança",
    landmark_title: "Selecione Ponto do Estádio",
    landmark_sub: "Clique em qualquer portão, estacionamento ou posto médico no mapa para ver filas, acessibilidade e rotas.",
    location_code: "Código de Localização",
    directions_title: "Calcular Rota",
    direct_path: "Rota Direta",
    ada_route: "Rota ADA",
    calculated_badge: "CALCULADA",
    starting_loc: "Ponto de partida simulado: Círculo Externo Seção 100.",

    // AI Assistant
    ai_title: "Assistente StadiumMind",
    ai_info_title: "Informações do Assistente de IA",
    ai_info_1: "Navegação Multilíngue: Traduz solicitações instantaneamente para guiar os torcedores por praças de alimentação, portões e transporte.",
    ai_info_2: "Mapeamento Conectado: Digitar 'Posto médico mais próximo' calculará a rota no painel do mapa automaticamente.",
    ai_info_3: "Acesso por Voz: Funções de assistência por voz e áudio guia para torcedores com deficiência visual ou auditiva.",
    ai_info_4: "Reciclagem Ecológica: Localiza máquinas de reciclagem reversa RVM e valida desafios de sustentabilidade.",
    ai_access_title: "Suporte de Acessibilidade",
    ai_access_desc: "Ative filtros de acessibilidade sensorial para mapear zonas silenciosas, elevadores ou rampas para cadeiras de rodas.",
    ai_placeholder: "Pergunte ao StadiumMind AI...",
    ai_listening: "Ouvindo pergunta...",

    // Command Center
    cc_title: "Centro de Comando de Segurança",
    cc_subtitle: "Centro de despacho operacional em tempo real e monitoramento por câmeras.",
    cc_threat: "IA de Detecção de Ameaças Multi-Câmeras",
    cc_active: "Incidentes Ativos e Despacho de Equipes",
    cc_no_incidents: "Nenhum incidente de segurança ou médico ativo. Estádio seguro.",
    cc_dispatch: "Despachar Equipe",
    cc_confirm: "Confirmar no Local",
    cc_resolve: "Marcar Resolvido",
    cc_gate_lock: "Painel de Controle de Portões",
    cc_lock_desc: "Substituir o status dos portões IoT durante bloqueios ou evacuações.",
    cc_report_alarm: "Relatar Alarme Local",
    cc_alarm_title: "Título do Alarme",
    cc_alarm_loc: "Localização no Estádio",
    cc_alarm_severity: "Nível de Gravidade",
    cc_alarm_log_btn: "Registrar Incidente",
    cc_logs: "Registro Operacional em Tempo Real",

    // Sustainability
    sus_title: "Inteligência Ecológica do Estádio",
    sus_subtitle: "Painel de telemetria verde mapeando rendimento solar, metas de reciclagem e gamificação de torcedores.",
    sus_score: "Sua Pontuação Eco",
    sus_points: "Pontos",
    sus_next_reward: "Próxima Recompensa: 300 pts",
    sus_redeem: "Resgatar voucher de lanchonete",
    sus_canopy_yield: "Rendimento do Telhado Solar",
    sus_canopy_desc: "Gerando 18.5% da carga elétrica atual do estádio.",
    sus_grid_power: "Energia da Rede",
    sus_offset: "Compensação: 34.2 ton CO₂",
    sus_recycle_target: "Meta de Reciclagem",
    sus_recycle_desc: "Meta: 70% de reciclagem de plásticos descartáveis do jogo.",
    sus_recycle_vending: "Reciclagem Reversa",
    sus_recycle_exceeding: "Superando Meta",
    sus_challenges: "Complete Desafios Ecológicos dos Torcedores",
    sus_claim_pts: "Resgatar Eco-Pontos",
    sus_completed: "Concluído",
    sus_solar_integration: "Integração Solar Renovável (Consumo kW)",
    sus_waste_analytics: "Análise de Resíduos (Toneladas)",
    sus_leaderboard: "Tabela de Classificação Eco",
    sus_you: "Você (Simulado)",

    // Auth
    auth_register: "Criar Conta",
    auth_signin: "Autenticar Credenciais",
    auth_fullname: "Nome Completo",
    auth_email: "Endereço de E-mail",
    auth_password: "Senha",
    auth_bypass: "Desvio Rápido para Desenvolvedor / Juiz",
    auth_processing: "Processando sessão...",
    auth_create_account: "Criar Conta",
    auth_toggle_create: "Não tem uma conta? Cadastre-se",
    auth_toggle_login: "Já tem uma conta? Entre",

    // Alerts
    alert_evac_title: "Evacuação de Emergência Ativa",
    alert_evac_desc: "Por favor, proceda com calma para os portões de saída abertos mais próximos: Saída Norte ou Saída Sul. Siga a equipe. NÃO USE ELEVADORES.",
    alert_sos_title: "Sinal de Emergência SOS Ativo",
    alert_sos_desc: "Sinalizador de emergência ativo próximo à Seção 220 Concourse. Equipe médica despachada.",
    alert_sos_clear: "Limpar SOS"
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('stadiummind_lang');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('stadiummind_lang', lang);
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations.en;
    return dict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
